schema_version = "1.0.0"

id = "r0tools_simple_toolbox_schedule_deferred_update_fix"
version = "0.3.4"
name = "r0Tools - Simple Toolbox.schedule-deferred-update-fix"
tagline = "General workflow utitlies"
maintainer = "https://github.com/r0fld4nc3"
# Supported types: "add-on", "theme"
type = "add-on"

website = "https://github.com/r0fld4nc3/blender-r0-simple-toolbox"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["3D View", "Modeling", "Mesh", "Object", "Pipeline"]

blender_version_min = "4.2.5"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# # https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = ["SPDX:GPL-3.0-or-later"]

paths_exclude_pattern = ["__pycache__/", "/.git/", "/*.zip"]
